### ISSUE TITLE
Ability to use objects with Shortcuts

### ISSUE THREAD

**Issue by sudogooglex** [scapain/dofustouch-noemu#13]
The 'ctrl+1', ..., 'ctrl+9' shortcuts are poping a window but you still have to click on 'use'.

[screenshot.png](https://drive.google.com/file/d/0B08OYS7z8Q8JMkN5Znl3U2Y0Q1E/view?usp=sharing)

**Comment by sudogooglex** [comment]
For some items(potions), it seems that double clicking the icon works fine. It could be possible to simulate a double click instead of a simple click.
But for other items (quick equipment), double click is not working.

**Comment by scapain** [comment]
Fix with the 3.0.1, we working on the simulation of a double click, but it's complicated
