### ISSUE TITLE
[3.0.1] - 2017-02-02. Bug : During a fight, you can't move / use shortkey

### ISSUE THREAD

**Issue by sudogooglex** [scapain/dofustouch-noemu#15]
Sometimes, during a fight, you can't move / use shortkey.
When disconecting / reconnecting, you either can move again / use shortkeys agin.

May be linked to the V3.
Linux

**Comment by scapain** [comment]
I working on init, it's happen when you deco/reco on a same tab. It will be fix soon, in the next update
