### ISSUE TITLE
Rendre le projet d'avantage open-source

### ISSUE THREAD

**Issue by TouchOnWeb** [scapain/dofustouch-noemu#2]
Etant donné que le projet est open source, pourquoi ne pas télécharger les mises à jours directement sur le repo en utilisant le système de releases ?
Cet auto-updater à l'air intéressant : https://github.com/GitbookIO/nuts

Idem pour le site web, mettre le code sur le git ?

**Comment by scapain** [comment]
Je suis d'accord avec l'idée de rendre le projet toujours plus open-source, je voulais déjà poser les bases.
J'avais déjà vu ce système d'auto updater seul bémol c'est qu'il n'assure aucun service pour linux...

**Comment by scapain** [comment]
Finalement il est impossible d'utiliser ce système car les applications de MàJ doivent être signés et cela est payant sur Windows..
