### ISSUE TITLE
[Amélioration] Pouvoir ajouter des notes sur une map

### ISSUE THREAD

**Issue by delmotte** [scapain/dofustouch-noemu#4]
Quand je fais du PVM, ça serait cool de pouvoir ajouter des notes sur une map pour pouvoir par exemple me rappeler que le placement est plutôt adapté pour un sacri, un cra, ...

**Comment by scapain** [comment]
Je ne sais pas si cela est possible en l'état, à voir.

**Comment by SwiTool** [comment]
Tu peux peut-être afficher les emplacements de combat sans être en combat, à voir aussi si c'est possible
