### ISSUE TITLE
[Amélioration] Selection de la langue

### ISSUE THREAD

**Issue by lenemson** [scapain/dofustouch-noemu#7]
J'ai l'impression que la langue est set en fonction de la langue du systeme, j'aimerai pouvoir choisir le français meme si mon pc est en anglais!

Si j'ai le temps j'essaierai peut etre de faire une PR

**Comment by zahiid** [comment]
Bah normalement oui , en haut à droite de l'écran d'authentification .

**Comment by lenemson** [comment]
Ah? serais-je aveugle? je regarderais ca ce soir merci :)

**Comment by lenemson** [comment]
C'est bon au faite, ya deja un moyen de changer la langue
